// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: myapps.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

public static partial class DataService
{
  static readonly string __ServiceName = "DataService";

  static readonly grpc::Marshaller<global::Application> __Marshaller_Application = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Application.Parser.ParseFrom);
  static readonly grpc::Marshaller<global::User> __Marshaller_User = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::User.Parser.ParseFrom);

  static readonly grpc::Method<global::Application, global::Application> __Method_CreateApplication = new grpc::Method<global::Application, global::Application>(
      grpc::MethodType.Unary,
      __ServiceName,
      "CreateApplication",
      __Marshaller_Application,
      __Marshaller_Application);

  static readonly grpc::Method<global::Application, global::Application> __Method_GetApplication = new grpc::Method<global::Application, global::Application>(
      grpc::MethodType.Unary,
      __ServiceName,
      "GetApplication",
      __Marshaller_Application,
      __Marshaller_Application);

  static readonly grpc::Method<global::User, global::User> __Method_GetUser = new grpc::Method<global::User, global::User>(
      grpc::MethodType.Unary,
      __ServiceName,
      "GetUser",
      __Marshaller_User,
      __Marshaller_User);

  static readonly grpc::Method<global::Application, global::Application> __Method_DeleteApplication = new grpc::Method<global::Application, global::Application>(
      grpc::MethodType.Unary,
      __ServiceName,
      "DeleteApplication",
      __Marshaller_Application,
      __Marshaller_Application);

  /// <summary>Service descriptor</summary>
  public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
  {
    get { return global::MyappsReflection.Descriptor.Services[0]; }
  }

  /// <summary>Base class for server-side implementations of DataService</summary>
  [grpc::BindServiceMethod(typeof(DataService), "BindService")]
  public abstract partial class DataServiceBase
  {
    public virtual global::System.Threading.Tasks.Task<global::Application> CreateApplication(global::Application request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

    public virtual global::System.Threading.Tasks.Task<global::Application> GetApplication(global::Application request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

    public virtual global::System.Threading.Tasks.Task<global::User> GetUser(global::User request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

    public virtual global::System.Threading.Tasks.Task<global::Application> DeleteApplication(global::Application request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

  }

  /// <summary>Client for DataService</summary>
  public partial class DataServiceClient : grpc::ClientBase<DataServiceClient>
  {
    /// <summary>Creates a new client for DataService</summary>
    /// <param name="channel">The channel to use to make remote calls.</param>
    public DataServiceClient(grpc::ChannelBase channel) : base(channel)
    {
    }
    /// <summary>Creates a new client for DataService that uses a custom <c>CallInvoker</c>.</summary>
    /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
    public DataServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
    {
    }
    /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
    protected DataServiceClient() : base()
    {
    }
    /// <summary>Protected constructor to allow creation of configured clients.</summary>
    /// <param name="configuration">The client configuration.</param>
    protected DataServiceClient(ClientBaseConfiguration configuration) : base(configuration)
    {
    }

    public virtual global::Application CreateApplication(global::Application request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return CreateApplication(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual global::Application CreateApplication(global::Application request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_CreateApplication, null, options, request);
    }
    public virtual grpc::AsyncUnaryCall<global::Application> CreateApplicationAsync(global::Application request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return CreateApplicationAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual grpc::AsyncUnaryCall<global::Application> CreateApplicationAsync(global::Application request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_CreateApplication, null, options, request);
    }
    public virtual global::Application GetApplication(global::Application request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return GetApplication(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual global::Application GetApplication(global::Application request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_GetApplication, null, options, request);
    }
    public virtual grpc::AsyncUnaryCall<global::Application> GetApplicationAsync(global::Application request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return GetApplicationAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual grpc::AsyncUnaryCall<global::Application> GetApplicationAsync(global::Application request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_GetApplication, null, options, request);
    }
    public virtual global::User GetUser(global::User request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return GetUser(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual global::User GetUser(global::User request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_GetUser, null, options, request);
    }
    public virtual grpc::AsyncUnaryCall<global::User> GetUserAsync(global::User request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return GetUserAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual grpc::AsyncUnaryCall<global::User> GetUserAsync(global::User request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_GetUser, null, options, request);
    }
    public virtual global::Application DeleteApplication(global::Application request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return DeleteApplication(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual global::Application DeleteApplication(global::Application request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_DeleteApplication, null, options, request);
    }
    public virtual grpc::AsyncUnaryCall<global::Application> DeleteApplicationAsync(global::Application request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return DeleteApplicationAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual grpc::AsyncUnaryCall<global::Application> DeleteApplicationAsync(global::Application request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_DeleteApplication, null, options, request);
    }
    /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
    protected override DataServiceClient NewInstance(ClientBaseConfiguration configuration)
    {
      return new DataServiceClient(configuration);
    }
  }

  /// <summary>Creates service definition that can be registered with a server</summary>
  /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
  public static grpc::ServerServiceDefinition BindService(DataServiceBase serviceImpl)
  {
    return grpc::ServerServiceDefinition.CreateBuilder()
        .AddMethod(__Method_CreateApplication, serviceImpl.CreateApplication)
        .AddMethod(__Method_GetApplication, serviceImpl.GetApplication)
        .AddMethod(__Method_GetUser, serviceImpl.GetUser)
        .AddMethod(__Method_DeleteApplication, serviceImpl.DeleteApplication).Build();
  }

  /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
  /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
  /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
  /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
  public static void BindService(grpc::ServiceBinderBase serviceBinder, DataServiceBase serviceImpl)
  {
    serviceBinder.AddMethod(__Method_CreateApplication, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Application, global::Application>(serviceImpl.CreateApplication));
    serviceBinder.AddMethod(__Method_GetApplication, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Application, global::Application>(serviceImpl.GetApplication));
    serviceBinder.AddMethod(__Method_GetUser, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::User, global::User>(serviceImpl.GetUser));
    serviceBinder.AddMethod(__Method_DeleteApplication, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Application, global::Application>(serviceImpl.DeleteApplication));
  }

}
#endregion
